### ISSUE TITLE
Inconsistent results from binary vs json stream query

### ISSUE THREAD

**Issue by wtflanders** [lf-edge/ekuiper#1219] opened 2022-04-05 18:46 UTC
I need to extract both the mqtt topic and the data from a stream in my rule.
It works if the stream is BINARY, it does NOT work if the stream is JSON.

This query works:
./kuiper create stream 'test_binary_stream() WITH ( datasource = "data/#", FORMAT= "BINARY", KEY = "id")'
with query:
SELECT mqtt(test_binary_stream.topic), self FROM test_binary_stream

This query does NOT work:
./kuiper create stream 'test_stream() WITH ( datasource = "data/#", FORMAT= "JSON", KEY = "id")'
SELECT mqtt(test_stream.topic), self FROM test_stream

**Environment**:
- eKuiper version (e.g. `1.4.2`)
- running in Docker image

**What happened and what you expected to happen**:
Query to BINARY and JSON streams should both work as the BINARY stream query does.

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:

**Comment by SuperRxan** [comment] 2022-04-07 03:38
Duplicate of #787

when 787 fixed, you should be able to write SQL like this

``select mqtt(test_stream.topic), * FROM test_stream``

**Closed** 2022-10-27 11:51 UTC
Labels: duplicate
