### ISSUE TITLE
MQTT 5.0

### ISSUE THREAD

**Issue by mrbluecoat** [lf-edge/ekuiper#3077] opened 2024-08-03 01:06 UTC
Any ETA for MQTT protocol version 5.0 support? https://ekuiper.org/docs/en/latest/guide/sinks/builtin/mqtt.html

**Comment by ngjaying** [comment] 2024-08-05 08:03
This is a duplicate of #1940. Please keep an eye on that issue. Thanks.

**Closed by ngjaying** 2024-08-05 08:03 UTC
