### ISSUE TITLE
Using sliding window no results output

### ISSUE THREAD

**Issue by wild-River2016** [lf-edge/ekuiper#3350] opened 2024-10-31 07:06 UTC
使用滑动窗口（SLIDINGWINDOW）创建温度持续30秒大于75度的规则，没有结果输出。
规则：
`select temp from stream1 group by SLIDINGWINDOW(ss,30,30) over (when temp > 75) having min(temp) > 75`
测试数据：
{"deviceId":100,"temp":70.1}
{"deviceId":100,"temp":76.1}
{"deviceId":100,"temp":77.1}
{"deviceId":100,"temp":79.1}
{"deviceId":100,"temp":79.1}
{"deviceId":100,"temp":79.1}
{"deviceId":100,"temp":80.1}

**Environment**:
- eKuiper version (e.g. `2.0.0`): 

**What happened and what you expected to happen**:
麻烦看一下配置规则是否正确，如何才能输出结果。
[期望能得到案例集锦中（总电流持续10s超过200A）的效果。](https://ekuiper.org/docs/zh/latest/example/change_data_capture.html)
![image](https://github.com/user-attachments/assets/5bc35890-2d1d-40c6-bcdd-fca2855190a8)

**Comment by evermon** [comment] 2024-11-27 23:00
Hello,

**Comment by ngjaying** [comment] 2024-12-05 03:24
After investigation, this is a duplicate of #3347 , so close it.

**Closed by ngjaying** 2024-12-05 03:24 UTC
